import type { SourceProfile } from '../v3/types.ts';

export const OIKO_V3_PIPELINE_VERSION = 'v3';

export const OIKO_V3_SOURCE_REGISTRY: Record<string, SourceProfile> = {
  'ecb.europa.eu': {
    sourceName: 'ECB',
    domain: 'ecb.europa.eu',
    sourceTier: 'official',
    sourceReliabilityScore: 1,
    sourceType: 'institution',
    paywallRisk: 0,
    snippetOnlyRisk: 0,
  },
  'federalreserve.gov': {
    sourceName: 'Federal Reserve',
    domain: 'federalreserve.gov',
    sourceTier: 'official',
    sourceReliabilityScore: 1,
    sourceType: 'institution',
    paywallRisk: 0,
    snippetOnlyRisk: 0,
  },
  'bls.gov': {
    sourceName: 'BLS',
    domain: 'bls.gov',
    sourceTier: 'official',
    sourceReliabilityScore: 1,
    sourceType: 'institution',
    paywallRisk: 0,
    snippetOnlyRisk: 0,
  },
  'bea.gov': {
    sourceName: 'BEA',
    domain: 'bea.gov',
    sourceTier: 'official',
    sourceReliabilityScore: 1,
    sourceType: 'institution',
    paywallRisk: 0,
    snippetOnlyRisk: 0,
  },
  'ec.europa.eu': {
    sourceName: 'European Commission / Eurostat',
    domain: 'ec.europa.eu',
    sourceTier: 'official',
    sourceReliabilityScore: 0.98,
    sourceType: 'institution',
    paywallRisk: 0,
    snippetOnlyRisk: 0.05,
  },
  'imf.org': {
    sourceName: 'IMF',
    domain: 'imf.org',
    sourceTier: 'official',
    sourceReliabilityScore: 0.98,
    sourceType: 'institution',
    paywallRisk: 0,
    snippetOnlyRisk: 0.1,
  },
  'oecd.org': {
    sourceName: 'OECD',
    domain: 'oecd.org',
    sourceTier: 'official',
    sourceReliabilityScore: 0.97,
    sourceType: 'institution',
    paywallRisk: 0,
    snippetOnlyRisk: 0.1,
  },
  'worldbank.org': {
    sourceName: 'World Bank',
    domain: 'worldbank.org',
    sourceTier: 'official',
    sourceReliabilityScore: 0.97,
    sourceType: 'institution',
    paywallRisk: 0,
    snippetOnlyRisk: 0.1,
  },
  'reuters.com': {
    sourceName: 'Reuters',
    domain: 'reuters.com',
    sourceTier: 'tier1',
    sourceReliabilityScore: 0.96,
    sourceType: 'wire',
    paywallRisk: 0.2,
    snippetOnlyRisk: 0.15,
  },
  'apnews.com': {
    sourceName: 'AP',
    domain: 'apnews.com',
    sourceTier: 'tier1',
    sourceReliabilityScore: 0.94,
    sourceType: 'wire',
    paywallRisk: 0.1,
    snippetOnlyRisk: 0.15,
  },
  'ft.com': {
    sourceName: 'Financial Times',
    domain: 'ft.com',
    sourceTier: 'tier1',
    sourceReliabilityScore: 0.95,
    sourceType: 'press',
    paywallRisk: 0.95,
    snippetOnlyRisk: 0.4,
  },
  'wsj.com': {
    sourceName: 'Wall Street Journal',
    domain: 'wsj.com',
    sourceTier: 'tier1',
    sourceReliabilityScore: 0.94,
    sourceType: 'press',
    paywallRisk: 0.95,
    snippetOnlyRisk: 0.45,
  },
  'bloomberg.com': {
    sourceName: 'Bloomberg',
    domain: 'bloomberg.com',
    sourceTier: 'tier1',
    sourceReliabilityScore: 0.94,
    sourceType: 'press',
    paywallRisk: 0.9,
    snippetOnlyRisk: 0.35,
  },
  'economist.com': {
    sourceName: 'The Economist',
    domain: 'economist.com',
    sourceTier: 'tier1',
    sourceReliabilityScore: 0.93,
    sourceType: 'analysis',
    paywallRisk: 0.95,
    snippetOnlyRisk: 0.4,
  },
  'cnbc.com': {
    sourceName: 'CNBC',
    domain: 'cnbc.com',
    sourceTier: 'tier2',
    sourceReliabilityScore: 0.82,
    sourceType: 'press',
    paywallRisk: 0.15,
    snippetOnlyRisk: 0.2,
  },
  'marketwatch.com': {
    sourceName: 'MarketWatch',
    domain: 'marketwatch.com',
    sourceTier: 'tier2',
    sourceReliabilityScore: 0.78,
    sourceType: 'press',
    paywallRisk: 0.35,
    snippetOnlyRisk: 0.25,
  },
  'bbc.com': {
    sourceName: 'BBC',
    domain: 'bbc.com',
    sourceTier: 'tier2',
    sourceReliabilityScore: 0.86,
    sourceType: 'press',
    paywallRisk: 0,
    snippetOnlyRisk: 0.15,
  },
  'bbc.co.uk': {
    sourceName: 'BBC',
    domain: 'bbc.co.uk',
    sourceTier: 'tier2',
    sourceReliabilityScore: 0.86,
    sourceType: 'press',
    paywallRisk: 0,
    snippetOnlyRisk: 0.15,
  },
  'theguardian.com': {
    sourceName: 'The Guardian',
    domain: 'theguardian.com',
    sourceTier: 'tier2',
    sourceReliabilityScore: 0.81,
    sourceType: 'press',
    paywallRisk: 0,
    snippetOnlyRisk: 0.18,
  },
  'politico.eu': {
    sourceName: 'Politico Europe',
    domain: 'politico.eu',
    sourceTier: 'tier2',
    sourceReliabilityScore: 0.8,
    sourceType: 'press',
    paywallRisk: 0.2,
    snippetOnlyRisk: 0.2,
  },
  'lesechos.fr': {
    sourceName: 'Les Echos',
    domain: 'lesechos.fr',
    sourceTier: 'tier2',
    sourceReliabilityScore: 0.84,
    sourceType: 'press',
    paywallRisk: 0.7,
    snippetOnlyRisk: 0.3,
  },
  'lemonde.fr': {
    sourceName: 'Le Monde',
    domain: 'lemonde.fr',
    sourceTier: 'tier2',
    sourceReliabilityScore: 0.83,
    sourceType: 'press',
    paywallRisk: 0.55,
    snippetOnlyRisk: 0.25,
  },
  'english.kyodonews.net': {
    sourceName: 'Kyodo News',
    domain: 'english.kyodonews.net',
    sourceTier: 'tier2',
    sourceReliabilityScore: 0.8,
    sourceType: 'wire',
    paywallRisk: 0.1,
    snippetOnlyRisk: 0.2,
  },
  'livemint.com': {
    sourceName: 'Mint',
    domain: 'livemint.com',
    sourceTier: 'secondary',
    sourceReliabilityScore: 0.62,
    sourceType: 'press',
    paywallRisk: 0.45,
    snippetOnlyRisk: 0.35,
  },
  'economictimes.indiatimes.com': {
    sourceName: 'The Economic Times',
    domain: 'economictimes.indiatimes.com',
    sourceTier: 'secondary',
    sourceReliabilityScore: 0.58,
    sourceType: 'press',
    paywallRisk: 0.45,
    snippetOnlyRisk: 0.4,
  },
  'thehindubusinessline.com': {
    sourceName: 'BusinessLine',
    domain: 'thehindubusinessline.com',
    sourceTier: 'secondary',
    sourceReliabilityScore: 0.56,
    sourceType: 'press',
    paywallRisk: 0.3,
    snippetOnlyRisk: 0.35,
  },
  'abc.net.au': {
    sourceName: 'ABC Australia',
    domain: 'abc.net.au',
    sourceTier: 'tier2',
    sourceReliabilityScore: 0.82,
    sourceType: 'press',
    paywallRisk: 0,
    snippetOnlyRisk: 0.18,
  },
};

export const OIKO_V3_POLICY = {
  version: 'v3.0.0',
  rollout: {
    shadowEnabled: String(process.env.OIKO_V3_SHADOW_ENABLED || 'false').toLowerCase() === 'true',
    publicEnabled: String(process.env.OIKO_V3_PUBLIC_ENABLED || 'false').toLowerCase() === 'true',
    pipelineVersion: OIKO_V3_PIPELINE_VERSION,
    internalConsecutiveDaysRequired: 5,
  },
  collection: {
    minimumSourceReliability: 0.78,
    allowedSourceTiers: ['official', 'tier1', 'tier2'] as const,
    maxSnippetOnlyRisk: 0.34,
    supportingSecondaryMinimumReliability: 0.55,
    supportingSecondaryMaxSnippetOnlyRisk: 0.45,
    supportingSecondarySignalPatterns: [
      'oil',
      'crude',
      'fuel costs',
      'gas supplies',
      'inflation fears',
      'rate-cut',
      'rates',
      'market sell-off',
      'bond yields',
      'energy shock',
      'petrol',
      'airline',
      'shipping',
      'strait of hormuz',
      'safe haven',
      'currency',
      'tariff',
    ],
    supportingSecondaryExcludePatterns: [
      'top most traded stocks',
      'most traded stocks',
      'nse today',
      'world sugar prices',
      'us-based analyst',
    ],
    hardExcludeTitlePatterns: [
      'what to expect',
      "here's how",
      'know how',
      'trading setup',
      'editorial board',
      'opinion',
      'personal finance',
      'mutual fund',
      'stock market in trade',
      'advance tax',
      'municipal bonds',
    ],
  },
  acquisition: {
    requestTimeoutMs: 12000,
    minimumFullBodyChars: 1600,
    minimumPartialBodyChars: 480,
    minimumReadableChars: 320,
    minimumReadableSentences: 3,
    minimumReadableParagraphs: 2,
    maxBoilerplateRatio: 0.28,
    blockedPaywallScore: 0.9,
    allowUnknownRobotsAsBlocked: false,
    userAgent: process.env.WIKIMEDIA_USER_AGENT || 'OikoNews/1.0 (+https://localhost)',
    boilerplateMarkers: [
      'subscribe',
      'sign in',
      'view market dashboard',
      'top sections',
      'view more',
      'view less',
      "today's paper",
      'market dashboard',
      'cookie policy',
      'privacy policy',
      'terms of use',
      'all rights reserved',
      'premium offerings',
      'tools and calculators',
      'multi media collections',
      'dark mode',
      'please let us know',
      'look back at how the trading session unfolded',
      'specialist business reporters',
      'this blog is not intended as investment advice',
      "that's it for another day on the blog",
      "we'll be back early tomorrow",
      'what a great day for bears',
    ],
  },
  scoring: {
    minimumHighQualitySourceReliability: 0.82,
    minimumOfficialSourceReliability: 0.95,
    contextOnlyPenalty: 1.25,
    lowDepthPenalty: 0.85,
    freshnessWeight: 0.35,
    importanceWeight: 0.2,
    sourceQualityWeight: 0.2,
    confidenceWeight: 0.15,
    diversityWeight: 0.1,
  },
  freshness: {
    minimumFreshEventCount: 4,
    minimumDistinctClusterCount: 3,
    minimumFreshSentenceShare: 0.7,
    maxContextOnlyShare: 0.3,
  },
  facts: {
    minimumFactsPerArticle: 2,
    maximumFactsPerArticle: 6,
    freshSignalPatterns: [
      'appoints',
      'approved',
      'approves',
      'freeze',
      'frozen',
      'halt',
      'halts',
      'hits',
      'holds rates',
      'jump',
      'jumps',
      'named',
      'names',
      'plunges',
      'posts',
      'surge',
      'surges',
      'spike',
      'spikes',
      'drop',
      'drops',
      'rise',
      'rises',
      'fall',
      'falls',
      'sheds',
      'slides',
      'published',
      'released',
      'announced',
      'reported',
      'warned',
      'cut',
      'raised',
      'deal',
      'talks',
      'sanctions',
      'ceasefire',
      'strike',
      'threatens',
      'withdraw',
      'tariff',
      'cpi',
      'jobs report',
      'payrolls',
      'gdp',
    ],
    updateSignalPatterns: [
      'update',
      'latest',
      'extended losses',
      'under pressure',
      'amid',
      'after',
      'following',
      'as markets',
    ],
    backgroundSignalPatterns: [
      'blog',
      'paper',
      'study',
      'research',
      'background',
      'analysis',
      'explainer',
      "here's why",
      'here is why',
      'more pain ahead',
      'what does it imply',
      'what it means',
      '1970s-like',
      'reminds analysts',
      'outlook',
    ],
    staleSignalPatterns: [
      'what to expect',
      "here's how",
      'know how',
      'opinion',
      'editorial',
      'explainer',
      'trading setup',
      'personal finance',
      'how to attract investors',
      "here's why",
      'more pain ahead',
      '1970s-like',
      'reminds analysts',
      'what it means',
      'what does it imply',
    ],
  },
  originality: {
    exactConsecutiveTokenOverlap: 12,
    maxParagraphOverlapRatio: 0.42,
    maxSentenceTitleSimilarity: 0.72,
    maxMonoArticleSectionRatio: 0.8,
    minSupportedFactsPerMajorParagraph: 2,
    minSupportedFactsPerBrief: 1,
  },
  language: {
    maxEnglishSentences: 0,
    maxMixedLanguageSentences: 0,
    minimumFrenchScore: 0.9,
  },
  publication: {
    requireHighQualitySources: 2,
    requireOfficialOrTrusted: 1,
    supportedSentenceRatio: 1,
    forbiddenResidueCount: 0,
  },
  repair: {
    maxRepairPasses: 1,
  },
  assets: {
    minimumCoverageForBonus: 0.5,
    brokenAssetsBlockPublication: true,
  },
  residuePatterns: [
    'read full story',
    'read full article',
    'only in paid plans',
    'only available in paid plans',
    'gift nifty',
    'click here to read',
    'subscribe to continue',
  ],
};

export function normalizeDomain(domain: string) {
  return String(domain || '').trim().toLowerCase().replace(/^www\./, '');
}

export function getSourceProfile(domain: string, sourceName = ''): SourceProfile {
  const normalizedDomain = normalizeDomain(domain);
  if (OIKO_V3_SOURCE_REGISTRY[normalizedDomain]) {
    return OIKO_V3_SOURCE_REGISTRY[normalizedDomain];
  }

  return {
    sourceName: sourceName || normalizedDomain || 'Source inconnue',
    domain: normalizedDomain,
    sourceTier: 'secondary',
    sourceReliabilityScore: 0.45,
    sourceType: 'press',
    paywallRisk: 0.5,
    snippetOnlyRisk: 0.5,
  };
}

export function isHighQualitySource(profile: SourceProfile) {
  return profile.sourceReliabilityScore >= OIKO_V3_POLICY.scoring.minimumHighQualitySourceReliability
    && (profile.sourceTier === 'official' || profile.sourceTier === 'tier1' || profile.sourceTier === 'tier2');
}
